<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'e.g. http://documentserver' => '',
    '<strong>Create</strong> document' => '<strong>Criar</strong> documento',
    '<strong>DocumentServer</strong> not accessible.' => '<strong>Servidor de Documentos</strong> não acessível.',
    '<strong>DocumentServer</strong> not configured yet.' => '<strong>Servidor de Documentos</strong> não configurado.',
    '<strong>DocumentServer</strong> successfully connected! - Installed version: {version}' => '<strong>Servidor de Documentos</strong> conectado com sucesso! - Versão instalada: {version}',
    '<strong>OnlyOffice - DocumentServer</strong> module configuration' => '<strong>Servidor de Documentos - OnlyOffice</strong> Módulo de Configuração',
    '<strong>Share</strong> document' => '<strong>Compartilhar</strong> documento',
    'Close' => 'Fechar',
    'Copy to clipboard' => 'Copiar para área de transferência',
    'Could not find requested file!' => 'Não foi possível encontrar o arquivo solicitado!',
    'Could not find shared file!' => 'Não foi possível encontrar o arquivo compartilhado!',
    'File read access denied!' => 'Acesso de leitura ao arquivo negado!',
    'File write access denied!' => 'Acesso de escrita ao arquivo negado!',
    'Hostname' => 'Servidor',
    'Link for view only access' => 'Link para acesso apenas de visualização',
    'Link with enabled write access' => 'Link para acesso com permissão de escrita',
    'Open the new document in the next step' => 'Abrir o novo documento no próximo passo',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => 'Você pode simplesmente compartilhar esse documento usando um link direto. O usuário não precisa de uma conta válida na plataforma.',
];
