<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '',
    '<strong>DocumentServer</strong> not accessible.' => '',
    '<strong>DocumentServer</strong> not configured yet.' => '',
    '<strong>DocumentServer</strong> successfully connected! - Installed version: {version}' => '',
    '<strong>OnlyOffice - DocumentServer</strong> module configuration' => '',
    '<strong>Share</strong> document' => '',
    'Close' => '',
    'Copy to clipboard' => '',
    'Could not find requested file!' => '',
    'Could not find shared file!' => '',
    'File read access denied!' => '',
    'File write access denied!' => '',
    'Hostname' => '',
    'Link for view only access' => '',
    'Link with enabled write access' => '',
    'Open the new document in the next step' => '',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => '',
    'e.g. http://documentserver' => '',
];
